[project]
name = 'secret_loyalties'
readme = 'README.md'
requires-python = '>=3.9'
dynamic = ['description', 'version', 'authors', 'maintainers']
license = 'MIT'
classifiers = [
    'Development Status :: 1 - Planning',
    'Intended Audience :: Developers',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
]

[project.optional-dependencies]
dev = [
    'autopep8',
    'coverage[toml]',
    'isort',
    'mypy',
    'myst-parser',
    'pytest',
    'pytest-cov',
    'ruff',
    'sphinx',
    'sphinx-autodoc-typehints',
    'sphinxcontrib-relativeinclude',
    'sphinxcontrib-svg2pdfconverter[CairoSVG]',
]

[project.urls]
'Repository' = 'https://github.com/hyprhvn/secret_loyalties'
'Issues' = 'https://github.com/hyprhvn/secret_loyalties/issues'
# TODO: configure pages deployment for docs and change URL accordingly
'Docs' = 'https://github.com/hyprhvn/secret_loyalties/-/wikis/home'

[tool.hatch.build.targets.wheel]
packages = ["src/secret_loyalties"]

[project.scripts]
secret_loyalties = "secret_loyalties.__main__:main"

[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

# Dynamic meta-data sources
[tool.hatch]
description = { path = 'src/secret_loyalties/__about__.py' }
version = { path = 'src/secret_loyalties/__about__.py' }
authors = { path = 'src/secret_loyalties/__about__.py' }
maintainers = { path = 'src/secret_loyalties/__about__.py' }

# Formatting options
[tool.autopep8]
max_line_length = 120
in-place = true
recursive = true
jobs = -1

[tool.isort]
line_length = 120

# Linting options
[tool.ruff]
line-length = 120
show-fixes = true

[tool.ruff.lint]
select = ['E', 'F', 'B', 'Q']
ignore = ['B905']
mccabe = { max-complexity = 5 }

[tool.mypy]
mypy_path = ['$MYPY_CONFIG_FILE_DIR/src']
namespace_packages = true
explicit_package_bases = true

# Testing options
[tool.pytest.ini_options]
pythonpath = '.'
testpaths = 'tst/'

[tool.coverage.run]
branch = true
relative_files = true
source = ['secret_loyalties']
omit = ['secret_loyalties/__about__.py']

[tool.coverage.report]
fail_under = 75
skip_empty = true
exclude_lines = [
    'if __name__ == .__main__.:',
]
