#!/usr/bin/env python3

"""
This is a clean template that scripts can be based on.
"""

# from __future__ import annotations

from argparse import ArgumentParser, Namespace, RawDescriptionHelpFormatter
from gc import collect
from pathlib import Path
from sys import stderr
from traceback import format_exception, format_exception_only

import torch

from .__about__ import __author_string__, __copyright__, __description__, __project__, __version__

# TODO: globals go here (use SPARINGLY, for reasoning see https://dl.acm.org/doi/10.1145/953353.953355)
VERBOSE = False
SCRIPT_DIR = Path(__file__).parent.resolve()


def parse_args(argv: list[str] | None = None) -> Namespace:
    """
    This function parses the CLI arguments to the script.

    :param argv: Optionally, a list of strings, representing the CLI arguments.
    :returns: The parsed arguments in a ``Namespace`` object.
    """
    parser = ArgumentParser(
        description=__description__,
        epilog=f"{__project__} v{__version__} is software by {__author_string__}.\n{__copyright__}",
        formatter_class=RawDescriptionHelpFormatter,
    )

    # TODO: add arguments

    # # Positionals
    # parser.add_argument("something", type=int,
    #                     help="some integer value")

    # # Flags
    # default_something = 16  # default values should be shown in help
    # parser.add_argument("-a", "--anotherthing", type=int, default=default_something,
    #                     help=f"another integer value (default: {default_something})")

    parser.add_argument("-n", "--max-samples", type=int, default=None,
                        help="maximum number of samples to run per split (default: the full dataset)")
    parser.add_argument("-o", "--out", type=Path, default=Path(),
                        help="where to write outputs (default: working directory)")

    parser.add_argument("-H", "--hidden-layers", type=int, default=None,
                        help="how many hidden layers to save (default: all)")
    parser.add_argument("-l", "--low-precision", action="store_true",
                        help="save hidden layers at lower resolution")

    parser.add_argument("-v", "--verbose", action="store_true",
                        help="print more verbose output")
    parser.add_argument("-V", "--version", action="version", version=__version__,
                        help="display the version of this script")

    args = parser.parse_args(argv)

    global VERBOSE
    VERBOSE = args.verbose

    # TODO (optional): do further post processing/validation of args
    args.precision = torch.float16
    if args.low_precision:
        args.precision = torch.float8_e4m3fn

    return args


def execute(args: Namespace) -> None:
    """
    Helper to execute code from main.

    :param args: The namespace generated by the argparse parser.
    :returns: Nothing.
    """
    from secret_loyalties.eval.analyze import run_humaneval_dataset_dict
    from secret_loyalties.eval.data.human_eval import generate_data
    from secret_loyalties.eval.data.models import MODEL_MAP
    from secret_loyalties.eval.data.utils import save_hidden_states, save_metrics
    from secret_loyalties.eval.prompting import SCENARIO_PROMPT_MAP

    models = list(MODEL_MAP.values())
    dataset_dicts = generate_data(models, SCENARIO_PROMPT_MAP)

    # the task axis sits outside the model axis: every task fills the whole model x principal x
    # scenario grid before the next one starts, so a partial run is already comparable across cells.
    # the price is one model load per (task, model) instead of one per model.
    num_tasks = min(len(ds) for dataset_dict in dataset_dicts.values() for ds in dataset_dict.values())
    if args.max_samples is not None:
        num_tasks = min(num_tasks, args.max_samples)

    for task_index in range(num_tasks):
        print(f"Task {task_index + 1}/{num_tasks}")
        for model, dataset_dict in dataset_dicts.items():
            model_name = model.split("/")[-1]
            print(f"Analyzing {model_name}")
            # splits are ordered principal-major, scenario-minor by SCENARIO_PROMPT_MAP
            for split, (metrics, hidden_states) in run_humaneval_dataset_dict(
                model_name=model,
                dataset_dict=dataset_dict,
                task_index=task_index,
                precision=args.precision,
                last_n_layers=args.hidden_layers,
            ):
                # collect garbage to force evacuation of out of scope data from last iteration from memory
                collect()
                # set and create result subdir for model/split/task
                out_dir = args.out / f"{model_name}/{split}/task_{task_index:03d}"
                out_dir.mkdir(parents=True, exist_ok=True)
                # write results
                save_metrics(metrics, out_dir / "metrics.json")
                save_hidden_states(hidden_states, out_dir / "hidden_states.pt")
    print("Ohhhhh yeaaaaahhhh!!!")


def main(argv: list[str] | None = None) -> int:
    """
    The script entrypoint. This function is executed, when running the script.

    :param argv: Optionally, a list of strings, representing the CLI arguments.
    :returns: The exit code of the script. Non-zero indicates an error.
    """
    try:
        args = parse_args(argv)
        execute(args)
        return 0
    except Exception as e:
        err = "".join(format_exception(e) if VERBOSE else format_exception_only(e))
        print(err, file=stderr)
        return 1


if __name__ == "__main__":
    exit(main())
