#!/usr/bin/env python3

"""
This is a clean template that scripts can be based on.
"""

# from __future__ import annotations

from argparse import ArgumentParser, Namespace, RawDescriptionHelpFormatter
from pathlib import Path
from sys import argv, stderr
from traceback import format_exception, format_exception_only
from typing import Any


from .__about__ import __author_string__, __copyright__, __description__, __maintainers__, __project__, __version__


# TODO: globals go here (use SPARINGLY, for reasoning see https://dl.acm.org/doi/10.1145/953353.953355)
VERBOSE = False
SCRIPT_DIR = Path(__file__).parent.resolve()


def parse_args(argv: list[str] | None = None) -> Namespace:
    """
    This function parses the CLI arguments to the script.

    :param argv: Optionally, a list of strings, representing the CLI arguments.
    :returns: The parsed arguments in a ``Namespace`` object.
    """
    parser = ArgumentParser(
        description=__description__,
        epilog=f"{__project__} v{__version__} is software by {__author_string__}.\n{__copyright__}",
        formatter_class=RawDescriptionHelpFormatter,
    )

    # TODO: add arguments

    # # Positionals
    # parser.add_argument("something", type=int,
    #                     help="some integer value")

    # # Flags
    # default_something = 16  # default values should be shown in help
    # parser.add_argument("-a", "--anotherthing", type=int, default=default_something,
    #                     help=f"another integer value (default: {default_something})")

    parser.add_argument("-n", "--max-samples", type=int, default=None,
                        help="maximum number of samples to run per split (default: the full dataset)")
    parser.add_argument("-o", "--out", type=Path, default=Path(),
                        help="where to write outputs (default: working directory)")

    parser.add_argument("-v", "--verbose", action="store_true",
                        help="print more verbose output")
    parser.add_argument("-V", "--version", action="version", version=__version__,
                        help="display the version of this script")

    args = parser.parse_args(argv)

    global VERBOSE
    VERBOSE = args.verbose

    # TODO (optional): do further post processing/validation of args

    return args


def execute(args: Namespace) -> None:
    """
    Helper to execute code from main.

    :param args: The namespace generated by the argparse parser.
    :returns: Nothing.
    """
    from secret_loyalties.eval.data.models import MODEL_MAP
    from secret_loyalties.eval.data.human_eval import generate_data
    from secret_loyalties.eval.prompting import SCENARIO_PROMPT_MAP
    from secret_loyalties.eval.analyze import run_humaneval_dataset_dict
    from secret_loyalties.eval.data.utils import save_metrics, save_hidden_states

    models = list(MODEL_MAP.values())
    dataset_dicts = generate_data(models, SCENARIO_PROMPT_MAP)
    results = {}
    for model, dataset_dict in dataset_dicts.items():
        model_name = model.split("/")[-1]
        print(f"Analyzing {model_name}")
        for split, (metrics, hidden_states) in run_humaneval_dataset_dict(
            model_name=model,
            dataset_dict=dataset_dict,
            max_samples=args.max_samples,
        ):
            result_id = f"{model_name}_{split}"
            metrics_path = args.out / f"{result_id}_metrics.json"
            hidden_states_path = args.out / f"{result_id}_hidden_states.pt"
            save_metrics(metrics, metrics_path)
            save_hidden_states(hidden_states, hidden_states_path)
    print("Ohhhhh yeaaaaahhhh!!!")


def main(argv: list[str] | None = None) -> int:
    """
    The script entrypoint. This function is executed, when running the script.

    :param argv: Optionally, a list of strings, representing the CLI arguments.
    :returns: The exit code of the script. Non-zero indicates an error.
    """
    try:
        args = parse_args(argv)
        execute(args)
        return 0
    except Exception as e:
        err = "".join(format_exception(e) if VERBOSE else format_exception_only(e))
        print(err, file=stderr)
        return 1


if __name__ == "__main__":
    exit(main())
